name: aws_s3_client
description: Client library to interact with the AWS S3 API
version: 0.0.1
homepage: https://github.com/idrats/aws_s3_client

environment:
  sdk: '>=2.0.0-dev.58.0 <3.0.0'

dependencies:
  meta: ^1.1.5
  crypto: ^2.0.6
  http_client: ^0.5.0
  xml: ^3.0.1

dev_dependencies:
  test: ^1.0.0
